### PR TITLE
Implement `out, ISR`

### PR DESCRIPTION
**Pull request by aaronjamt**
These methods were already implemented so I just added them to the list of `out, ...` destinations.

### CODE REVIEW

**Comment by NathanY3G** [comment]
Thank you @aaronjamt! I have just seen your MR and will look at it soon :slightly_smiling_face:

**Comment by aaronjamt** [comment]
I fixed the merge conflict, should be ready now. LGTM

**Comment by NathanY3G** [comment]
@aaronjamt I hope to finish reviewing your PR soon. I have added and merged a test for  `OUT PC` and will add one for `OUT ISR` next.

**Comment by NathanY3G** [comment]
I have added a test to [test_out.py](https://github.com/NathanY3G/rp2040-pio-emulator/blob/main/tests/instructions/test_out.py) which should hopefully help. It is currently disabled to prevent build failures on `main`.

**Comment by aaronjamt** [comment]
I'll try to sort this out first and then I can help with type hints if that still needs work

**Comment by aaronjamt** [comment]
Fixed now, I ran the tests and it works. I've also included a commit to re-enable the OUT ISR tests

**Review by NathanY3G — COMMENTED** [review]
Thanks again @aaronjamt :+1:

**Pull request merged**
